#spring.application.name: provider-application
#spring.profiles.active: local
#configVar: configVar-application-file
#
#---
#spring.profiles: local
#configVar: configVar-application-local
#
#---
#spring.profiles: pro-1
#configVar: configVar-application-pro-1