spring:
  datasource:
    url: spring.datasource.url=jdbc:h2:tcp://localhost/~/test
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /console

