
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rjornelas/spring-cloud-microservice-studies/tree/master/microservice-repo
          search-paths: provider